# Generated by Django 2.2.5 on 2019-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20190919_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='short_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
