# Generated by Django 2.2.5 on 2019-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_stripeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconfig',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripeconfig',
            name='card_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeconfig',
            name='connect_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeconfig',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
