# Generated by Django 2.2.5 on 2019-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20191030_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconfig',
            name='connect_account_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
