# Generated by Django 2.2.5 on 2019-11-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_stripeconfig_connect_account_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
