# Generated by Django 2.2.5 on 2019-11-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_fund_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconfig',
            name='source_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
