# Generated by Django 2.2.5 on 2019-11-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20191102_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCEEDED'), (2, 'FAILED'), (3, 'REFUNDED')], default=0),
        ),
    ]
