# Generated by Django 2.2.5 on 2019-11-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20191104_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='stripe_refund_id',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='proposals.Fund')),
            ],
            options={
                'verbose_name_plural': 'Refunds',
                'ordering': ['created'],
            },
        ),
    ]
