# Generated by Django 2.2.5 on 2019-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_fund_amount_og'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'DECLINED')], default=0),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCEEDED'), (2, 'FAILED')], default=0),
        ),
    ]
