# Generated by Django 2.2.5 on 2019-11-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_tx_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='next_tx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_tx', to='proposals.Tx'),
        ),
    ]
