# Generated by Django 2.2.5 on 2019-11-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_auto_20191106_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='fund',
        ),
        migrations.AddField(
            model_name='tx',
            name='detached_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detach_tx', to='proposals.Bid'),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
