# Generated by Django 2.2.5 on 2019-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_auto_20191107_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'DECLINED')], default=0),
        ),
    ]
