# Generated by Django 2.2.5 on 2019-11-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_auto_20191108_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tx',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCEEDED'), (2, 'FAILED'), (3, 'CANCELLED')], default=0),
        ),
    ]
