# Generated by Django 2.2.5 on 2019-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_auto_20191108_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
