# Generated by Django 2.2.5 on 2019-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_auto_20191108_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='vote_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vote_positive',
            field=models.IntegerField(default=0),
        ),
    ]
