# Generated by Django 2.2.5 on 2019-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_auto_20191109_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='vote_score',
            field=models.FloatField(default=0),
        ),
    ]
