# Generated by Django 2.2.5 on 2019-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_auto_20191109_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='vote_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='vote_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='vote_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote_score',
            field=models.FloatField(default=0),
        ),
    ]
