# Generated by Django 2.2.5 on 2019-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_auto_20191109_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='instant_payment_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='max_tx_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='min_tx_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='step_amount_cents',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
