# Generated by Django 2.2.5 on 2019-11-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_auto_20191110_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='short_text',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED'), (3, 'PENDING'), (4, 'DECLINED')], default=1),
        ),
    ]
