# Generated by Django 2.2.5 on 2019-11-13 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0029_auto_20191113_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'PENDING'), (2, 'ACTIVE'), (3, 'DECLINED'), (4, 'DELETED'), (5, 'PAID'), (6, 'FULFILLED')], default=1)),
                ('vote_score', models.FloatField(default=0)),
                ('vote_total', models.IntegerField(default=0)),
                ('vote_positive', models.PositiveIntegerField(default=0)),
                ('vote_negative', models.PositiveIntegerField(default=0)),
                ('is_proposal', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(related_name='collab_access', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg', to=settings.AUTH_USER_MODEL)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_versions', to='proposals.Msg')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='proposals.Msg')),
            ],
            options={
                'verbose_name_plural': 'Proposals',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MsgVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_votes', to=settings.AUTH_USER_MODEL)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='proposals.Msg')),
            ],
        ),
        migrations.CreateModel(
            name='MsgBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_threshold', models.PositiveIntegerField(default=3)),
                ('expiration', models.DateTimeField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='proposals.Msg')),
            ],
        ),
    ]
