# Generated by Django 2.2.5 on 2019-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0030_msg_msgbid_msgvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msgbid',
            old_name='bid',
            new_name='msg',
        ),
        migrations.AlterField(
            model_name='msgbid',
            name='amount_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
