# Generated by Django 2.2.5 on 2019-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_auto_20191113_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='amount_threshold',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='msg',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'PENDING'), (2, 'ACTIVE'), (3, 'DECLINED'), (4, 'DELETED'), (5, 'PAID'), (6, 'FULFILLED'), (7, 'PREVIOUS_VERSION')], default=1),
        ),
        migrations.DeleteModel(
            name='MsgBid',
        ),
    ]
