# Generated by Django 2.2.5 on 2019-11-14 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0032_auto_20191114_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='update_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
