# Generated by Django 2.2.5 on 2019-11-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0034_msgtx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgtx',
            name='stripe_refund_id',
        ),
    ]
