# Generated by Django 2.2.5 on 2019-11-21 22:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0035_remove_msgtx_stripe_refund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='root',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='root_comment',
        ),
        migrations.RemoveField(
            model_name='tx',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='tx',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tx',
            name='detached_bid',
        ),
        migrations.RemoveField(
            model_name='tx',
            name='next_tx',
        ),
        migrations.RemoveField(
            model_name='tx',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='proposal',
        ),
        migrations.AddField(
            model_name='msg',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Tx',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
