# Generated by Django 2.2.5 on 2019-11-30 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0037_auto_20191130_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.PositiveSmallIntegerField(choices=[(0, 'NEW_REPLY'), (1, 'BID_PAID'), (2, 'BID_FULFILLED'), (3, 'USER_MENTION')], default=0)),
                ('msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='proposals.Msg')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
