# Generated by Django 2.2.5 on 2019-12-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_msgnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='collab_str',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
